### ISSUE TITLE
[BODY] Separate positions for feet

### ISSUE THREAD

**Issue by FreyaIthildur** [Collaboratives/MeshbodyFeatureRequests#38] opened 2023-04-08 20:15 UTC
**Is your feature request related to a problem? Please describe.**
Customers would want to use separate positions for feet

**Describe the solution you'd like**
L and R controls

**Is there an alternative solution until feature implementation?**
No.

**Comment by Collaboratives** [comment] 2023-04-09 17:32
Duplicate of https://github.com/Collaboratives/MeshbodyFeatureRequests/issues/17

**Closed by Collaboratives** 2023-04-09 17:32 UTC
